source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

xcodeproj 'FPAQuickStart'

target :FPAQuickStart do
  pod 'AFNetworking', '~> 4.0'
  pod 'CocoaAsyncSocket', '~> 7.6.5'
  pod 'AgoraFPA_iOS', '~> 1.0.0'
end
